### ISSUE TITLE
Downloads page leads to confusion

### ISSUE THREAD

**Issue by kaixoo** [friction2d/friction2d.github.io#1]
Current downloads section leads to confusion,as there are two identical sections with just one tiny difference: the version number. Furthermore, if you don't scroll enough, it may seem as if stable version is the only version existing.

![image](https://github.com/user-attachments/assets/aaf930f5-df86-4386-b302-7b4a3f39bd0b)

I propose to put the two sections in columns side to side.

P.S: For SEO, \<h1\> should only be used once for the title of a page.

**Comment by kaixoo** [comment]
Here's what can be done for little

![image](https://github.com/user-attachments/assets/9f479e3c-dc11-4dde-90e4-f9df22ea9086)

**Comment by rodlie** [comment]
Beta download has been removed, "confusion" fixed.

**Comment by kaixoo** [comment]
Nooo, this is not a solution :(( beta downloads are meant to test new features and report bugs. Reopen

**Comment by rodlie** [comment]
Fine, I added it back with a minor modification:
![Screenshot from 2024-10-27 20-57-06](https://github.com/user-attachments/assets/00362364-8625-45b5-b4c2-4855170c63a6)
