### ISSUE TITLE
Experimental macOS build

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction2d.github.io#2]
I've seen in the b2 release notes that you don't want to provide macOS builds, but if you go to GitHub it's possible to get the dmg...

Do you want to delete it or are you at the end letting people try it out?
BTW, if you decide the last you could rename it so that it stays clearer what files belongs to the macOS build as just using the dmg extension won't let average users get what file to download... 😉

**Comment by rodlie** [comment]
> I've seen in the b2 release notes that you don't want to provide macOS builds

![Screenshot from 2024-12-03 00-25-12](https://github.com/user-attachments/assets/6ee2d85f-eefa-47b3-b887-1c73ebca25b7)

**Comment by pgilfernandez** [comment]
Great!
