### ISSUE TITLE
Documentation 404 pages

### ISSUE THREAD

**Issue by luzpaz** [friction2d/friction2d.github.io#4]
https://friction.graphics/documentation/source-windows.html  
https://friction.graphics/documentation/source-linux.html  
https://friction.graphics/documentation/shaders/  
https://friction.graphics/documentation/shortcuts.html

**Comment by rodlie** [comment]
> [https://friction.graphics/documentation/source-windows.html](https://friction.graphics/documentation/source-windows.html)
> https://friction.graphics/documentation/source-linux.html
> https://friction.graphics/documentation/shortcuts.html

Fixed.

> https://friction.graphics/documentation/shaders/

Moved to https://friction.graphics/documentation/shaders.html
